// <auto-generated />
using System;
using Aarshjul.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Aarshjul.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260619215745_Fase3Generering")]
    partial class Fase3Generering
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Aarshjul.Domain.BehandletDokument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BehandletStatus")
                        .HasColumnType("int");

                    b.Property<string>("DokumentNokkel")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTimeOffset>("ForstSett")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("InnholdHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kilde")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset?>("SisteForsoek")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Tittel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UttrekksForsoek")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Kilde", "DokumentNokkel")
                        .IsUnique();

                    b.ToTable("BehandledeDokumenter");
                });

            modelBuilder.Entity("Aarshjul.Domain.Bruker", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("ErFin")
                        .HasColumnType("bit");

                    b.Property<int>("Funksjonsrolle")
                        .HasColumnType("int");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("Brukere");
                });

            modelBuilder.Entity("Aarshjul.Domain.BrukerGruppe", b =>
                {
                    b.Property<string>("BrukerId")
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("GruppeKode")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("Kilde")
                        .HasColumnType("int");

                    b.HasKey("BrukerId", "GruppeKode");

                    b.HasIndex("GruppeKode");

                    b.ToTable("BrukerGrupper");
                });

            modelBuilder.Entity("Aarshjul.Domain.Forslag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Budsjettaar")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("Dato")
                        .HasColumnType("date");

                    b.Property<int?>("Datokvalifikator")
                        .HasColumnType("int");

                    b.Property<int>("Datopresisjon")
                        .HasColumnType("int");

                    b.Property<Guid?>("DokumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EndrerFristId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ForeslaattSynlighet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ForslagType")
                        .HasColumnType("int");

                    b.Property<int>("Kategori")
                        .HasColumnType("int");

                    b.Property<string>("KildeEllerInnsender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Loep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Opphav")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Tittel")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("Id");

                    b.HasIndex("EndrerFristId");

                    b.ToTable("Forslag");
                });

            modelBuilder.Entity("Aarshjul.Domain.Frist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Budsjettaar")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Dato")
                        .HasColumnType("date");

                    b.Property<int?>("Datokvalifikator")
                        .HasColumnType("int");

                    b.Property<int>("Datopresisjon")
                        .HasColumnType("int");

                    b.Property<Guid?>("DokumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ForeslaattAv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("GjentaRegelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Kategori")
                        .HasColumnType("int");

                    b.Property<string>("Kilde")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Loep")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Notat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Opphav")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Sorteringsdag")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Tittel")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("Id");

                    b.HasIndex("Budsjettaar");

                    b.HasIndex("Sorteringsdag");

                    b.ToTable("Frister");
                });

            modelBuilder.Entity("Aarshjul.Domain.FristSynlighet", b =>
                {
                    b.Property<Guid>("FristId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GruppeKode")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("FristId", "GruppeKode");

                    b.HasIndex("GruppeKode");

                    b.ToTable("FristSynlighet");
                });

            modelBuilder.Entity("Aarshjul.Domain.Gjentaksregel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Kategori")
                        .HasColumnType("int");

                    b.Property<string>("Loep")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Regelparametre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Regeltype")
                        .HasColumnType("int");

                    b.Property<string>("Tittel")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<bool>("Valgaarssensitiv")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Gjentaksregler");
                });

            modelBuilder.Entity("Aarshjul.Domain.InnhentingsStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Kilde")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("SisteFeilmelding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("SisteForsoek")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("SisteUtfall")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("SisteVellykkedeHenting")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("SisteVellykkedeOppdagelse")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Kilde")
                        .IsUnique();

                    b.ToTable("InnhentingsStatuser");
                });

            modelBuilder.Entity("Aarshjul.Domain.Synlighetsgruppe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Aktiv")
                        .HasColumnType("bit");

                    b.Property<bool>("ErStandard")
                        .HasColumnType("bit");

                    b.Property<string>("Kode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Kode")
                        .IsUnique();

                    b.ToTable("Synlighetsgrupper");
                });

            modelBuilder.Entity("Aarshjul.Domain.UttrekksBevis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Felt")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("ForslagId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Kildeutdrag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Konfidens")
                        .HasColumnType("float");

                    b.Property<string>("TolketVerdi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ForslagId");

                    b.ToTable("UttrekksBevis");
                });

            modelBuilder.Entity("Aarshjul.Domain.Varsel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Begrunnelse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BrukerId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("Lest")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("Opprettet")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Tekst")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BrukerId");

                    b.ToTable("Varsler");
                });

            modelBuilder.Entity("Aarshjul.Domain.BrukerGruppe", b =>
                {
                    b.HasOne("Aarshjul.Domain.Bruker", "Bruker")
                        .WithMany("Grupper")
                        .HasForeignKey("BrukerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aarshjul.Domain.Synlighetsgruppe", "Gruppe")
                        .WithMany()
                        .HasForeignKey("GruppeKode")
                        .HasPrincipalKey("Kode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bruker");

                    b.Navigation("Gruppe");
                });

            modelBuilder.Entity("Aarshjul.Domain.FristSynlighet", b =>
                {
                    b.HasOne("Aarshjul.Domain.Frist", "Frist")
                        .WithMany("Synlighet")
                        .HasForeignKey("FristId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aarshjul.Domain.Synlighetsgruppe", "Gruppe")
                        .WithMany()
                        .HasForeignKey("GruppeKode")
                        .HasPrincipalKey("Kode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Frist");

                    b.Navigation("Gruppe");
                });

            modelBuilder.Entity("Aarshjul.Domain.UttrekksBevis", b =>
                {
                    b.HasOne("Aarshjul.Domain.Forslag", "Forslag")
                        .WithMany("UttrekksBevis")
                        .HasForeignKey("ForslagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Forslag");
                });

            modelBuilder.Entity("Aarshjul.Domain.Bruker", b =>
                {
                    b.Navigation("Grupper");
                });

            modelBuilder.Entity("Aarshjul.Domain.Forslag", b =>
                {
                    b.Navigation("UttrekksBevis");
                });

            modelBuilder.Entity("Aarshjul.Domain.Frist", b =>
                {
                    b.Navigation("Synlighet");
                });
#pragma warning restore 612, 618
        }
    }
}
